import type {
  Appointment,
  AuditEvent,
  CaseStudy,
  Conversation,
  DrugItem,
  ExamQuestion,
  MetricCardData,
  PatientCase,
  ResearchPaper,
  VideoItem,
} from '../types'

export const demoMetrics: MetricCardData[] = [
  { label: 'Active patients', value: 18, helper: 'Fast local fallback data' },
  { label: 'Urgent cases', value: 4, helper: 'Needs same-day follow-up' },
  { label: 'AI drafts', value: 7, helper: 'Referral + treatment outputs' },
  { label: 'Study threads', value: 12, helper: 'Saved across roles' },
]

export const demoCases: PatientCase[] = [
  {
    id: 'case-1',
    patient_id: 'pat-1',
    doctor_id: 'doc-1',
    patient_name: 'Patient Demo User',
    age: 29,
    sex: 'Female',
    chief_complaint: 'Pain in lower right molar while chewing for 4 days',
    specialty: 'Endodontics',
    severity: 'URGENT',
    status: 'active',
    last_activity_at: new Date().toISOString(),
  },
  {
    id: 'case-2',
    patient_id: 'pat-2',
    doctor_id: 'doc-1',
    patient_name: 'Rahul Mehta',
    age: 34,
    sex: 'Male',
    chief_complaint: 'Severe toothache upper left, pain radiating to ear',
    specialty: 'Endodontics',
    severity: 'URGENT',
    status: 'active',
    last_activity_at: new Date(Date.now() - 1000 * 60 * 40).toISOString(),
  },
  {
    id: 'case-3',
    patient_id: 'pat-3',
    doctor_id: 'doc-1',
    patient_name: 'Sunita Patel',
    age: 52,
    sex: 'Female',
    chief_complaint: 'Loose teeth, bleeding gums, halitosis',
    specialty: 'Periodontics',
    severity: 'ROUTINE',
    status: 'review',
    last_activity_at: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
  },
  {
    id: 'case-4',
    patient_id: 'pat-4',
    doctor_id: 'doc-1',
    patient_name: 'Arjun Nair',
    age: 19,
    sex: 'Male',
    chief_complaint: 'Swelling near impacted lower third molar with trismus and fever',
    specialty: 'Oral Surgery',
    severity: 'URGENT',
    status: 'escalated',
    last_activity_at: new Date(Date.now() - 1000 * 60 * 18).toISOString(),
  },
  {
    id: 'case-5',
    patient_id: 'pat-5',
    doctor_id: 'doc-1',
    patient_name: 'Meera Joshi',
    age: 45,
    sex: 'Female',
    chief_complaint: 'Persistent non-healing white patch on right buccal mucosa',
    specialty: 'Oral Medicine',
    severity: 'URGENT',
    status: 'review',
    last_activity_at: new Date(Date.now() - 1000 * 60 * 75).toISOString(),
  },
  {
    id: 'case-6',
    patient_id: 'pat-6',
    doctor_id: 'doc-1',
    patient_name: 'Kabir Shah',
    age: 12,
    sex: 'Male',
    chief_complaint: 'Deep caries and nocturnal pain in lower left deciduous molar',
    specialty: 'Pediatric Dentistry',
    severity: 'ROUTINE',
    status: 'scheduled',
    last_activity_at: new Date(Date.now() - 1000 * 60 * 180).toISOString(),
  },
]

export const demoAppointments: Appointment[] = [
  {
    id: 'appt-1',
    patient_id: 'pat-1',
    doctor_id: 'doc-1',
    appointment_date: new Date(Date.now() + 1000 * 60 * 60 * 4).toISOString(),
    duration_minutes: 30,
    type: 'Emergency consult',
    status: 'confirmed',
    patient_name: 'Patient Demo User',
    contact_number: '+91 98765 43210',
    clinic_location: 'Operatory 2, Dental.ai Clinic',
    notes: 'IOPA + sensibility testing',
  },
  {
    id: 'appt-2',
    patient_id: 'pat-3',
    doctor_id: 'doc-1',
    appointment_date: new Date(Date.now() + 1000 * 60 * 60 * 24).toISOString(),
    duration_minutes: 45,
    type: 'Periodontal review',
    status: 'scheduled',
    patient_name: 'Sunita Patel',
    contact_number: '+91 98123 11009',
    clinic_location: 'Perio Bay, Floor 1',
    notes: 'Pocket depth reassessment',
  },
  {
    id: 'appt-3',
    patient_id: 'pat-2',
    doctor_id: 'doc-1',
    appointment_date: new Date(Date.now() + 1000 * 60 * 60 * 9).toISOString(),
    duration_minutes: 40,
    type: 'Endodontic pain review',
    status: 'confirmed',
    patient_name: 'Rahul Mehta',
    contact_number: '+91 99110 22110',
    clinic_location: 'Endo Suite, Chair 3',
    notes: 'Pulp vitality testing and pain control review',
  },
  {
    id: 'appt-4',
    patient_id: 'pat-4',
    doctor_id: 'doc-1',
    appointment_date: new Date(Date.now() + 1000 * 60 * 60 * 2).toISOString(),
    duration_minutes: 50,
    type: 'OMFS emergency triage',
    status: 'confirmed',
    patient_name: 'Arjun Nair',
    contact_number: '+91 98200 22110',
    clinic_location: 'Surgery Consult Room',
    notes: 'Assess airway, swelling spread, and extraction planning',
  },
  {
    id: 'appt-5',
    patient_id: 'pat-5',
    doctor_id: 'doc-1',
    appointment_date: new Date(Date.now() + 1000 * 60 * 60 * 36).toISOString(),
    duration_minutes: 30,
    type: 'Oral lesion review',
    status: 'scheduled',
    patient_name: 'Meera Joshi',
    contact_number: '+91 99880 66441',
    clinic_location: 'Oral Medicine Desk',
    notes: 'Habit history and lesion documentation',
  },
  {
    id: 'appt-6',
    patient_id: 'pat-6',
    doctor_id: 'doc-1',
    appointment_date: new Date(Date.now() + 1000 * 60 * 60 * 72).toISOString(),
    duration_minutes: 35,
    type: 'Pedo restorative visit',
    status: 'scheduled',
    patient_name: 'Kabir Shah',
    contact_number: '+91 97000 55443',
    clinic_location: 'Pedo Corner',
    notes: 'Behavior guidance + pulpotomy discussion',
  },
]

export const demoAudit: AuditEvent[] = [
  {
    id: 'audit-1',
    case_id: 'case-1',
    doctor_id: 'doc-1',
    event_type: 'triage',
    event_title: 'Urgent molar pain triage accepted',
    action_status: 'accepted',
    severity: 'URGENT',
    created_at: new Date().toISOString(),
  },
  {
    id: 'audit-2',
    case_id: 'case-3',
    doctor_id: 'doc-1',
    event_type: 'referral',
    event_title: 'Periodontal referral prepared',
    action_status: 'modified',
    severity: 'ROUTINE',
    created_at: new Date(Date.now() - 1000 * 60 * 90).toISOString(),
  },
  {
    id: 'audit-3',
    case_id: 'case-4',
    doctor_id: 'doc-1',
    event_type: 'appointment',
    event_title: 'Surgery consult slot created after urgent triage',
    action_status: 'accepted',
    severity: 'URGENT',
    created_at: new Date(Date.now() - 1000 * 60 * 12).toISOString(),
  },
  {
    id: 'audit-4',
    case_id: 'case-5',
    doctor_id: 'doc-1',
    event_type: 'clinical_note',
    event_title: 'Oral lesion flagged for same-week review and imaging',
    action_status: 'accepted',
    severity: 'URGENT',
    created_at: new Date(Date.now() - 1000 * 60 * 35).toISOString(),
  },
]

export const demoConversations: Conversation[] = [
  {
    id: 'conv-1',
    title: 'Molar pain triage plan',
    mode: 'Practitioner',
    updated_at: new Date().toISOString(),
    messages: [
      {
        id: 'msg-1',
        role: 'assistant',
        content: 'Assess pulpal status, take an IOPA, and plan urgent pain relief followed by definitive endodontic treatment.',
      },
    ],
  },
  {
    id: 'conv-2',
    title: 'Vertucci classification revision',
    mode: 'Student',
    updated_at: new Date(Date.now() - 1000 * 60 * 180).toISOString(),
    messages: [
      {
        id: 'msg-2',
        role: 'assistant',
        content: 'Type I to VIII summary with common exam traps ready to review.',
      },
    ],
  },
]

export const demoDrugs: DrugItem[] = [
  {
    id: 'amoxicillin',
    genericName: 'Amoxicillin',
    brandNames: ['Novamox', 'Amoxil'],
    className: 'Aminopenicillin antibiotic',
    dentalDose: '500 mg TDS for 5 to 7 days',
    commonDentalUse: 'Odontogenic infection and prophylaxis in selected patients',
    contraindications: ['Penicillin allergy', 'Infectious mononucleosis'],
    sideEffects: ['Nausea', 'Diarrhoea', 'Rash'],
  },
  {
    id: 'metronidazole',
    genericName: 'Metronidazole',
    brandNames: ['Metrogyl', 'Flagyl'],
    className: 'Nitroimidazole antibiotic',
    dentalDose: '400 mg TDS for 5 to 7 days',
    commonDentalUse: 'Anaerobic infections and pericoronitis',
    contraindications: ['Alcohol use', 'First trimester pregnancy'],
    sideEffects: ['Metallic taste', 'Nausea', 'Headache'],
  },
  {
    id: 'ibuprofen',
    genericName: 'Ibuprofen',
    brandNames: ['Brufen', 'Ibugesic'],
    className: 'NSAID',
    dentalDose: '400 mg TDS after food',
    commonDentalUse: 'Acute dental pain and post-operative inflammation',
    contraindications: ['Active peptic ulcer', 'NSAID allergy'],
    sideEffects: ['Gastric irritation', 'Fluid retention'],
  },
]

export const demoVideos: VideoItem[] = [
  {
    id: 'video-1',
    title: 'Rotary endodontics full protocol',
    channel: 'Dentsply Academy',
    specialty: 'Endodontics',
    duration: '24:31',
    views: '128K',
    thumbnailUrl: 'https://images.unsplash.com/photo-1588776814546-daab30f310ce?auto=format&fit=crop&w=1200&q=80',
    videoUrl: 'https://www.youtube.com/results?search_query=rotary+endodontics+protocol',
    playlist: 'Endodontics Essentials',
    topic: 'Access, glide path, shaping, irrigation',
  },
  {
    id: 'video-2',
    title: 'Periodontal staging and grading in clinic',
    channel: 'Perio Mastery',
    specialty: 'Periodontics',
    duration: '18:45',
    views: '89K',
    thumbnailUrl: 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?auto=format&fit=crop&w=1200&q=80',
    videoUrl: 'https://www.youtube.com/results?search_query=periodontal+staging+grading+clinic',
    playlist: 'Perio Clinic Workflow',
    topic: 'Classification, charting, maintenance',
  },
  {
    id: 'video-3',
    title: 'IOPA interpretation for chairside diagnosis',
    channel: 'Radiology Rounds',
    specialty: 'Oral Radiology',
    duration: '14:10',
    views: '64K',
    thumbnailUrl: 'https://images.unsplash.com/photo-1576091160550-2173dba999ef?auto=format&fit=crop&w=1200&q=80',
    videoUrl: 'https://www.youtube.com/results?search_query=IOPA+interpretation+dental',
    playlist: 'Radiology Chairside',
    topic: 'IOPA, OPG, lesion pattern review',
  },
  {
    id: 'video-4',
    title: 'Third molar extraction instrumentation walkthrough',
    channel: 'OMFS Basics',
    specialty: 'Oral Surgery',
    duration: '27:22',
    views: '172K',
    thumbnailUrl: 'https://images.unsplash.com/photo-1606811971618-4486d14f3f99?auto=format&fit=crop&w=1200&q=80',
    videoUrl: 'https://www.youtube.com/results?search_query=third+molar+extraction+instrumentation',
    playlist: 'OMFS Emergency Series',
    topic: 'Impactions, flaps, sectioning, safety',
  },
  {
    id: 'video-5',
    title: 'BDS exam strategy: how to retain viva answers',
    channel: 'Student Clinician',
    specialty: 'Exam Prep',
    duration: '11:08',
    views: '41K',
    thumbnailUrl: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?auto=format&fit=crop&w=1200&q=80',
    videoUrl: 'https://www.youtube.com/results?search_query=dental+viva+exam+strategy',
    playlist: 'Exam Mode Sprint',
    topic: 'Recall maps, viva prep, last-week revision',
  },
]

export const fallbackResearch: ResearchPaper[] = [
  {
    id: 'paper-1',
    title: 'AI-assisted caries detection on bitewing radiographs',
    authors: 'Sharma et al.',
    journal: 'Dentomaxillofacial Radiology',
    year: '2024',
    abstract: 'AI models continue to improve proximal caries detection and can support faster chairside review when paired with clinician oversight.',
    link: 'https://pubmed.ncbi.nlm.nih.gov/',
  },
  {
    id: 'paper-2',
    title: 'Single-visit versus multi-visit endodontic treatment outcomes',
    authors: 'Patel et al.',
    journal: 'Journal of Endodontics',
    year: '2024',
    abstract: 'Outcome differences remain small in well-selected cases, with case selection and asepsis still dominating success.',
    link: 'https://pubmed.ncbi.nlm.nih.gov/',
  },
  {
    id: 'paper-3',
    title: 'Peri-implant mucositis maintenance protocols in supportive therapy',
    authors: 'Fernandes et al.',
    journal: 'Clinical Oral Implants Research',
    year: '2024',
    abstract: 'Structured maintenance intervals and early inflammation control were associated with lower progression risk in implant patients.',
    link: 'https://pubmed.ncbi.nlm.nih.gov/',
  },
  {
    id: 'paper-4',
    title: 'Adjunctive AI support in oral lesion screening pathways',
    authors: 'Kumar et al.',
    journal: 'Oral Diseases',
    year: '2024',
    abstract: 'AI triage may improve documentation quality and referral timing when used alongside clinician review.',
    link: 'https://pubmed.ncbi.nlm.nih.gov/',
  },
]

export const demoCaseStudies: CaseStudy[] = [
  {
    id: 'case-study-1',
    title: 'Managing acute symptomatic irreversible pulpitis in a diabetic patient',
    authorName: 'Dr. Demo User',
    authorId: 'doc-1',
    specialty: 'Endodontics',
    summary: 'Chairside pain control, antibiotic stewardship, and staged treatment planning for a medically complex patient.',
    content: '<h2>Background</h2><p>This case focused on rapid pain relief with tight medical history review.</p><h2>Approach</h2><p>IOPA, vitality testing, occlusal relief, and definitive endodontic sequencing were used.</p>',
    views: 128,
    helpfulCount: 17,
    publishedAt: new Date().toISOString(),
    contentType: 'case_study',
    authorRole: 'doctor',
    coverImage: 'https://images.unsplash.com/photo-1666214280557-f1b5022eb634?auto=format&fit=crop&w=1200&q=80',
    readTime: '6 min read',
  },
  {
    id: 'case-study-2',
    title: 'How I revised oral pathology in 21 days before my viva',
    authorName: 'Aarohi Singh',
    authorId: 'stu-1',
    authorRole: 'student',
    specialty: 'Exam Strategy',
    summary: 'A structured student blog on building high-yield topic maps, viva answers, and last-week recall sheets.',
    content: '<h2>Week 1: Core lesion map</h2><p>I grouped white lesions, ulcerative lesions, and pigmented lesions into one recall tree.</p><h2>Week 2: Viva recall grid</h2><p>I practiced one definition, one differentiating point, and one biopsy indication for each lesion.</p><h2>Week 3: Rapid revision</h2><p>I used 20-minute loops with short oral answers and mnemonics.</p>',
    views: 214,
    helpfulCount: 49,
    publishedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString(),
    contentType: 'study_guide',
    coverImage: 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=1200&q=80',
    readTime: '5 min read',
  },
  {
    id: 'case-study-3',
    title: 'Chairside workflow for urgent facial swelling in general practice',
    authorName: 'Dr. Nikhil Rao',
    authorId: 'doc-2',
    authorRole: 'doctor',
    specialty: 'Emergency Workflow',
    summary: 'A medium-style operational guide for airway red flags, documentation, imaging, referral timing, and appointment sequencing.',
    content: '<h2>Triage first</h2><p>Check airway compromise, dysphagia, fever, and trismus before focusing on the tooth.</p><h2>Same-day actions</h2><p>Document spread, pain score, vitals if available, and organize immediate imaging and referral if indicated.</p><h2>Scheduling logic</h2><p>Emergency swelling gets a same-day consult slot, 24-hour review, and referral backup.</p>',
    views: 93,
    helpfulCount: 21,
    publishedAt: new Date(Date.now() - 1000 * 60 * 60 * 30).toISOString(),
    contentType: 'workflow',
    coverImage: 'https://images.unsplash.com/photo-1581594693702-fbdc51b2763b?auto=format&fit=crop&w=1200&q=80',
    readTime: '4 min read',
  },
]

export const examQuestions: ExamQuestion[] = [
  {
    id: 'q-1',
    prompt: 'Which tooth most commonly shows two canals that rejoin?',
    options: ['Mandibular first premolar', 'Maxillary canine', 'Mandibular central incisor', 'Maxillary first molar'],
    answer: 'Mandibular first premolar',
    explanation: 'It is notorious for variable anatomy and exam questions often test the possibility of split canals that rejoin.',
  },
  {
    id: 'q-2',
    prompt: 'In gingival health, sulcus depth is usually:',
    options: ['1 to 3 mm', '4 to 5 mm', '6 to 7 mm', 'Above 8 mm'],
    answer: '1 to 3 mm',
    explanation: 'Depths above 3 mm need clinical correlation for pocketing and attachment loss.',
  },
]
